"""Single read entry-point for cross-table "narrative entity" access.

Background
----------
The novel platform historically stored character-like data in three
independent places (see docs/database/database-source-of-truth-matrix.md):

* ``entities`` (novel_db) — the in-story state of a character: current
  objective, recent events, dialog voice.
* ``archive_library`` (archive) — the canon agent profile: core_drive,
  surface_mask, hidden_tension, template payload.
* ``assets`` with ``asset_type = 'character_archetype'`` — cross-project
  reusable templates.

Each of those is a legitimate concern, so the plan (approved 2026-04-18)
keeps them orthogonal but links them through:

* ``entities.archive_id`` / ``archive_library.entity_id`` soft FKs
  (alembic revision ``20260418_0002``)
* this service, which is the *only* place that knows how to combine them
  into a merged view.

Downstream consumers (``unified_asset_view.UnifiedAssetView.get_entity``,
``writer_agent.tool_executors.query_entity``) should call this service
instead of reading the three tables directly.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any

from sqlalchemy import Engine

from ..database import get_engine
from ..repositories.archive_repo import ArchiveRepository
from ..repositories.entity_repo import EntityRepository
from ..schemas.asset_types import AssetType
from .assets.assets_service import AssetsService


@dataclass
class MergedEntity:
    """Combined in-story + canon + template view of a single character.

    All three halves are optional: a character may have only an archive
    (generated by seed pipeline before any in-story entity exists), only
    an in-story entity (manually added in the writer workbench), or both.
    """

    name: str
    entity_type: str = ""
    project_id: str = ""

    # ---- in-story half (entities table) ----
    entity_id: str | None = None
    importance_tier: str = ""
    summary: str = ""
    current_objective: str = ""
    ultimate_goal: str = ""
    speech_style: str = ""
    entity_payload: dict[str, Any] = field(default_factory=dict)
    recent_events: list[dict[str, Any]] = field(default_factory=list)

    # ---- canon half (archive_library table) ----
    archive_id: str | None = None
    canon_profile: dict[str, Any] | None = None

    # ---- template references (assets.character_archetype) ----
    archetype_refs: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


class NarrativeEntityService:
    """Cross-table read access for character-like narrative entities.

    Only reads. Writes remain on the individual services
    (``EntityRepository`` / ``ArchiveLibraryService`` / ``AssetsService``).
    """

    def __init__(self, engine: Engine | None = None) -> None:
        engine = engine or get_engine()
        self._entity_repo = EntityRepository(engine)
        self._archive_repo = ArchiveRepository(engine)
        self._assets = AssetsService()

    # ------------------------------------------------------------------
    # Public lookup API
    # ------------------------------------------------------------------

    def get_by_name(self, project_id: str, name: str) -> MergedEntity | None:
        """Merge by common name (entity.name or archive.entity_name).

        Lookup order: entities by name → matching archive (via FK or name) →
        character_archetype assets whose title contains the name.
        """
        entity_row = self._entity_repo.get_entity_by_name(project_id, name)
        archive_row = self._find_archive(
            project_id=project_id,
            entity_id=(entity_row or {}).get("entity_id") if entity_row else None,
            name=name,
        )
        if entity_row is None and archive_row is None:
            return None
        return self._merge(project_id, entity_row, archive_row, name_hint=name)

    def get_by_entity_id(self, project_id: str, entity_id: str) -> MergedEntity | None:
        entity_row = self._entity_repo.get_entity(project_id, entity_id)
        if entity_row is None:
            return None
        archive_row = self._find_archive(
            project_id=project_id,
            entity_id=entity_id,
            name=entity_row.get("name", ""),
        )
        return self._merge(
            project_id,
            entity_row,
            archive_row,
            name_hint=entity_row.get("name", ""),
        )

    def get_by_archive_id(self, project_id: str, archive_id: str) -> MergedEntity | None:
        archive_row = self._archive_repo.get_archive(archive_id)
        if archive_row is None:
            return None
        entity_row = None
        archive_entity_id = archive_row.get("entity_id")
        if archive_entity_id:
            entity_row = self._entity_repo.get_entity(project_id, archive_entity_id)
        if entity_row is None:
            name = archive_row.get("entity_name") or ""
            if name:
                entity_row = self._entity_repo.get_entity_by_name(project_id, name)
        return self._merge(
            project_id,
            entity_row,
            archive_row,
            name_hint=archive_row.get("entity_name", ""),
        )

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _find_archive(
        self,
        *,
        project_id: str,
        entity_id: str | None,
        name: str,
    ) -> dict[str, Any] | None:
        """Locate the archive row that belongs to this in-story entity.

        Preference order:
          1. archive_library.entity_id == entity_id (new soft FK)
          2. entity.archive_id points to this archive (reverse soft FK)
          3. match by (project_id, entity_name == name)
        """
        archives = self._archive_repo.list_archives(project_id=project_id, limit=500)
        if entity_id:
            for row in archives:
                if row.get("entity_id") == entity_id:
                    return row
        if name:
            for row in archives:
                if row.get("entity_name") == name:
                    return row
        return None

    def _merge(
        self,
        project_id: str,
        entity_row: dict[str, Any] | None,
        archive_row: dict[str, Any] | None,
        *,
        name_hint: str,
    ) -> MergedEntity:
        merged = MergedEntity(
            name=(entity_row or {}).get("name")
            or (archive_row or {}).get("entity_name")
            or name_hint,
            project_id=project_id,
        )

        if entity_row:
            merged.entity_id = entity_row.get("entity_id")
            merged.entity_type = entity_row.get("entity_type") or ""
            merged.importance_tier = entity_row.get("importance_tier") or ""
            merged.summary = entity_row.get("summary") or ""
            merged.current_objective = entity_row.get("current_objective") or ""
            merged.ultimate_goal = entity_row.get("ultimate_goal") or ""
            merged.speech_style = entity_row.get("speech_style") or ""
            merged.entity_payload = dict(entity_row)
            eid = entity_row.get("entity_id")
            if eid:
                try:
                    merged.recent_events = list(
                        self._entity_repo.get_entity_recent_events(eid, limit=5) or []
                    )
                except Exception:
                    merged.recent_events = []

        if archive_row:
            merged.archive_id = archive_row.get("archive_id")
            # entity_type / importance_tier: archive wins only if entity side empty.
            if not merged.entity_type:
                merged.entity_type = archive_row.get("entity_type") or ""
            if not merged.importance_tier:
                merged.importance_tier = (
                    archive_row.get("selected_importance_tier")
                    or archive_row.get("importance_tier")
                    or ""
                )
            merged.canon_profile = {
                "entity_role": archive_row.get("entity_role") or "",
                "core_drive": archive_row.get("core_drive") or "",
                "surface_mask": archive_row.get("surface_mask") or "",
                "hidden_tension": archive_row.get("hidden_tension") or "",
                "relationship_summary": archive_row.get("relationship_summary") or "",
                "agent_behavior_hint": archive_row.get("agent_behavior_hint") or "",
                "template_key": archive_row.get("template_key") or "",
                "template_sections_json": archive_row.get("template_sections_json") or "[]",
                "template_payload_json": archive_row.get("template_payload_json") or "{}",
                "notable_risks_json": archive_row.get("notable_risks_json") or "[]",
            }

        # Archetype refs: enabled character_archetype assets (global + project)
        # whose title mentions the entity name. Small set — safe to scan.
        archetypes = self._assets.list_merged(
            project_id=project_id,
            asset_type=AssetType.CHARACTER_ARCHETYPE.value,
            enabled_only=True,
            limit=100,
        ) or []
        for a in archetypes:
            title = (a.get("title") or "").lower()
            if merged.name and merged.name.lower() in title:
                merged.archetype_refs.append(
                    {
                        "asset_id": a.get("asset_id"),
                        "title": a.get("title") or "",
                        "summary": a.get("summary") or "",
                        "scope": a.get("scope") or "",
                    }
                )
        return merged
