"""Worldline runtime and prepare tables."""

from __future__ import annotations

from .helpers import composite_pk, float_col, int_col, project_id, table, text_col

agent_registry = table("agent_registry", project_id(), text_col("session_id", nullable=False), text_col("branch_id", nullable=False), text_col("agent_id", nullable=False), text_col("agent_kind", nullable=False), text_col("display_name", nullable=False), text_col("source_ref", nullable=False), text_col("role", nullable=False), text_col("drive", nullable=False), text_col("tension", nullable=False), text_col("status", nullable=False), text_col("summary", nullable=False), int_col("can_chat", nullable=False), int_col("can_act", nullable=False), text_col("state_json", nullable=False), text_col("state_source", nullable=False), int_col("state_version", nullable=False), text_col("last_action_at"), text_col("last_dialogue_at"), text_col("source_archive_id"), text_col("source_entity_uuid"), text_col("importance_tier", nullable=False, default="'supporting'"), text_col("template_key", nullable=False, default="'generic.supporting.v1'"), text_col("template_version", nullable=False, default="'v1'"), text_col("template_sections_json", nullable=False, default="'[]'"), text_col("created_at", nullable=False), text_col("updated_at", nullable=False), composite_pk("project_id", "session_id", "branch_id", "agent_id"))
agent_state_snapshots = table("agent_state_snapshots", text_col("snapshot_id", primary_key=True), project_id(), text_col("session_id", nullable=False), text_col("branch_id", nullable=False), text_col("agent_id", nullable=False), int_col("state_version", nullable=False), text_col("status", nullable=False), text_col("reason", nullable=False), text_col("state_json", nullable=False), text_col("created_at", nullable=False))
agent_action_log = table("agent_action_log", text_col("action_event_id", primary_key=True), project_id(), text_col("session_id", nullable=False), text_col("branch_id", nullable=False), text_col("agent_id", nullable=False), text_col("display_name", nullable=False), text_col("action", nullable=False), text_col("intent", nullable=False), text_col("target", nullable=False), text_col("source", nullable=False), text_col("status", nullable=False), text_col("detail_json", nullable=False), text_col("created_at", nullable=False), text_col("applied_at"), text_col("discarded_at"))
agent_dialogue_log = table("agent_dialogue_log", text_col("dialogue_id", primary_key=True), project_id(), text_col("session_id", nullable=False), text_col("branch_id", nullable=False), text_col("agent_id", nullable=False), text_col("display_name", nullable=False), text_col("message", nullable=False), text_col("reply", nullable=False), text_col("generator_mode", nullable=False), text_col("model_name", nullable=False), text_col("context_summary", nullable=False), text_col("created_at", nullable=False))
relation_state_log = table("relation_state_log", text_col("relation_event_id", primary_key=True), project_id(), text_col("session_id", nullable=False), text_col("branch_id", nullable=False), text_col("agent_id", nullable=False), text_col("source_agent_id", nullable=False), text_col("target_agent_id", nullable=False), text_col("source_name", nullable=False), text_col("target_name", nullable=False), text_col("change", nullable=False), text_col("note", nullable=False), text_col("status", nullable=False), text_col("last_action", nullable=False), text_col("state_json", nullable=False), text_col("created_at", nullable=False))
agent_episodic_memory = table("agent_episodic_memory", text_col("memory_id", primary_key=True), project_id(), text_col("session_id", nullable=False), text_col("branch_id", nullable=False), text_col("agent_id", nullable=False), text_col("archive_id", nullable=False, default="''"), text_col("memory_type", nullable=False), text_col("summary", nullable=False), text_col("detail_json", nullable=False), text_col("source_kind", nullable=False), text_col("source_ref_id", nullable=False), text_col("normalized_subject", nullable=False), float_col("salience", nullable=False, default="0"), text_col("created_at", nullable=False), text_col("updated_at", nullable=False))
prepare_runs = table("prepare_runs", text_col("prepare_id", primary_key=True), text_col("task_id", nullable=False), project_id(nullable=True), text_col("graph_id", nullable=False), text_col("session_scope", nullable=False), text_col("status", nullable=False), text_col("stage", nullable=False), int_col("can_start", nullable=False, default="0"), text_col("focus_question", nullable=False), int_col("branch_count", nullable=False), text_col("source_summary_json", nullable=False), text_col("source_json", nullable=False), text_col("world_variables_json", nullable=False), text_col("input_payload_json", nullable=False), text_col("source_archive_ids_json", nullable=False), text_col("source_project_ids_json", nullable=False), int_col("source_archive_count", nullable=False, default="0"), text_col("started_session_id", nullable=False, default="''"), text_col("error"), text_col("created_at", nullable=False), text_col("updated_at", nullable=False))
prepared_agent_dossiers = table("prepared_agent_dossiers", project_id(nullable=True), text_col("prepare_id", nullable=False), text_col("agent_id", nullable=False), text_col("agent_kind", nullable=False), text_col("display_name", nullable=False), text_col("source_archive_id", nullable=False, default="''"), text_col("source_entity_uuid", nullable=False, default="''"), text_col("importance_tier", nullable=False), text_col("template_key", nullable=False), text_col("template_version", nullable=False), text_col("template_sections_json", nullable=False), text_col("model_name", nullable=False), text_col("validation_errors_json", nullable=False), text_col("public_profile_json", nullable=False), text_col("private_profile_json", nullable=False), text_col("runtime_seed_state_json", nullable=False), text_col("relationship_view_json", nullable=False), text_col("memory_seed_summary_json", nullable=False), text_col("source_evidence_summary_json", nullable=False), text_col("created_at", nullable=False), text_col("updated_at", nullable=False), composite_pk("prepare_id", "agent_id"))
prepare_event_log = table("prepare_event_log", text_col("event_id", primary_key=True), project_id(nullable=True), text_col("prepare_id", nullable=False), text_col("stage", nullable=False), text_col("level", nullable=False), text_col("message", nullable=False), text_col("detail_json", nullable=False), text_col("created_at", nullable=False))
worldline_sessions = table(
    "worldline_sessions",
    text_col("session_id", primary_key=True),
    project_id(nullable=True),
    text_col("graph_id", nullable=False, default="''"),
    text_col("session_scope", nullable=False, default="'project'"),
    text_col("label", nullable=False, default="''"),
    text_col("prepare_id", nullable=False, default="''"),
    text_col("status", nullable=False, default="'running'"),
    text_col("simulation_goal", nullable=False, default="''"),
    text_col("focus_question", nullable=False, default="''"),
    int_col("branch_count", nullable=False, default="1"),
    int_col("source_archive_count", nullable=False, default="0"),
    text_col("source_archive_ids_json", nullable=False, default="'[]'"),
    text_col("source_project_ids_json", nullable=False, default="'[]'"),
    text_col("session_data_json", nullable=False, default="'{}'"),
    text_col("created_at", nullable=False),
    text_col("updated_at", nullable=False),
)
